// import { useAuthUser, withAuthUser, withAuthUserSSR } from 'next-firebase-auth';
import Head from 'next/head';
// import firebase from 'firebase/app';
// import { db, auth } from '../firebase';
// import FireBae from '../FireBae';

// ar avea ceva sens sa facem mai ini static
// apoi cu harta aia pe about
// apoi sa incepem cu adminul si ui si auth si tot

const Home = () => {
  const test = () => {
    // db.collection('courses')
    //   .get()
    //   .then((querySnapshot) => {
    //     querySnapshot.forEach((doc) => {
    //       console.log(`${doc.id} => ${JSON.stringify(doc.data())}`);
    //     });
    //   })
    //   .catch((error) => {
    //     console.log(error);
    //   });
  };

  const authUser = useAuthUser();
  // console.log(authUser);

  // const login = () => {
  //   auth.signInWithEmailAndPassword('dragos.iordache@pixellab.ro', 'test123');
  // };

  // const register = () => {
  //   auth.createUserWithEmailAndPassword(
  //     'dragos.iordache@pixellab.ro',
  //     'test123',
  //   );
  // };

  // const logout = () => {
  //   auth.signOut();
  // };

  // const googleTest = () => {
  //   const provider = new firebase.auth.GoogleAuthProvider();

  auth
    .signInWithPopup(provider)
    .then((result) => {
      const userCredentials = result;
      db.collection('users').doc(userCredentials.user.uid).set({
        uid: userCredentials.user.uid,
        email: userCredentials.user.email,
        name: userCredentials.user.displayName,
        provider: userCredentials.user.providerData[0].providerId,
        photoUrl: userCredentials.user.photoURL,
      });
    })
    .catch((err) => {
      console.log(err);
    });

  return (
    <div className="text-green-800">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <button onClick={test}>TEST</button>
      HI!
      <br />
      <button onClick={register}>Create user</button>
      <br />
      <button
        onClick={() => {
          login();
        }}
      >
        sign int
      </button>
      <br />
      <button onClick={logout}>signout</button>
      <br />
      <button onClick={googleTest}>Sign with google</button> */}
      {/* <FireBae></FireBae> */}
    </div>
  );
};

// export const getServerSideProps = withAuthUserSSR()();

// export default withAuthUser()(Home);

export default Home;
