export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PROFILE_SET_COLOR = 'PROFILE_SET_COLOR';
export const PROFILE_SET_STATS = 'PROFILE_SET_STATS';
export const PROFILE_SET_COLORS = 'PROFILE_SET_COLORS';
